apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: sniff-dns
  labels:
    name: sniff-dns
spec:
  selector:
    matchLabels:
      name: sniff-dns
  template:
    metadata:
      labels:
        name: sniff-dns
    spec:
      hostNetwork: true
      tolerations:
      - key: node-role.kubernetes.io/master
        effect: NoSchedule
      containers:
      - name: debug
        image: jhansen/k8s-debug-pod:dns-0.1.0
        imagePullPolicy: Always
        command: ["tshark", "-f", "udp port 53"]
        resources:
          limits:
            memory: 200Mi
          requests:
            cpu: 100m
            memory: 200Mi
        securityContext:
          capabilities:
            add:
              - NET_ADMIN
      terminationGracePeriodSeconds: 30
