apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: debug-routes
  namespace: default
  labels:
    name: debug-routes
spec:
  selector:
    matchLabels:
      name: debug-routes
  template:
    metadata:
      labels:
        name: debug-routes
    spec:
      hostNetwork: true
      tolerations:
      - key: node-role.kubernetes.io/master
        effect: NoSchedule
      containers:
      - name: debug
        image: jhansen/k8s-debug-pod:latest
        imagePullPolicy: Always
        command: [ "/bin/sh", "-c", "while true; do date && ip route list && sleep ${POD_SLEEP_SECS}; done "]
        securityContext:
          capabilities:
            add:
              - NET_ADMIN
        env:
          - name: POD_SLEEP_SECS
            value: "600"
        resources:
          limits:
            memory: 200Mi
          requests:
            cpu: 100m
            memory: 200Mi
      terminationGracePeriodSeconds: 30
