apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: debug-ebtables
  namespace: default
  labels:
    name: debug-ebtables
spec:
  selector:
    matchLabels:
      name: debug-ebtables
  template:
    metadata:
      labels:
        name: debug-ebtables
    spec:
      hostNetwork: true
      tolerations:
      - key: node-role.kubernetes.io/master
        effect: NoSchedule
      containers:
      - name: debug
        image: jhansen/k8s-debug-pod:0.2.0
        command: [ "/bin/sh", "-c", "while true; do date && tail -200 /var/log/azure-cnimonitor.log; ebtables -t nat -L && ebtables -L && arp -na && sleep ${POD_SLEEP_SECS}; done "]
        securityContext:
          capabilities:
            add:
              - NET_ADMIN
        env:
          - name: POD_SLEEP_SECS
            value: "600"
        resources:
          limits:
            memory: 200Mi
          requests:
            cpu: 100m
            memory: 200Mi
        volumeMounts:
          - name: logs
            mountPath: /var/log
            readOnly: true
          - name: modules
            mountPath: /lib/modules
            readOnly: true
      terminationGracePeriodSeconds: 30
      volumes:
        - name: logs
          hostPath:
            path: /var/log
        - name: modules
          hostPath:
            path: /lib/modules
