#!/bin/bash

set -euo pipefail

# Validate the ARM template
send_metric() {
    metric_name=$1
    metric_value=$2

    metric=$( jq -nc \
                --arg iKey $INSTRUMENTATION_KEY \
                --arg datetime $(date -u +"%Y-%m-%dT%H:%M:%SZ") \
                --arg node_name $NODE_NAME \
                --arg pod_name $POD_NAME \
                --arg metric_name $metric_name \
                --arg metric_value $metric_value \
                -f debug-conntrack.jq )
    response=$(curl -Ss -d $metric https://dc.services.visualstudio.com/v2/track)
    errors=$(echo $response | jq -r '.errors | length')

    if [ "$errors" -ne "0" ]; then
        echo "[$(date)] ERROR: $response"
    fi
}

while true; do

    nf_conntrack_max=$(cat /host/sys/net/netfilter/nf_conntrack_max)
    nf_conntrack_count=$(cat /host/sys/net/netfilter/nf_conntrack_count)
    insert_failed=$(conntrack -S | grep -oEi 'insert_failed=[0-9]+' | cut -d '=' -f 2 | awk '{s+=$1} END {print s}')

    echo "[$(date)] nf_conntrack_max: $nf_conntrack_max, nf_conntrack_count: $nf_conntrack_count, insert_failed: $insert_failed"

    if [ ! -z "${INSTRUMENTATION_KEY-}" ]; then
        send_metric 'nf_conntrack_count' $nf_conntrack_count
        send_metric 'insert_failed' $insert_failed
    fi

    sleep "${POD_SLEEP_SECS}";
done
