apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: sniff-host
  labels:
    name: sniff-host
spec:
  selector:
    matchLabels:
      name: sniff-host
  template:
    metadata:
      labels:
        name: sniff-host
    spec:
      hostNetwork: true
      tolerations:
      - key: node-role.kubernetes.io/master
        effect: NoSchedule
      containers:
      - name: debug
        image: jhansen/k8s-debug-pod:dns-0.1.0
        imagePullPolicy: Always
        command: ["tshark", "-f", "host 40.71.17.19"]
        resources:
          limits:
            memory: 200Mi
          requests:
            cpu: 100m
            memory: 200Mi
        securityContext:
          capabilities:
            add:
              - NET_ADMIN
      terminationGracePeriodSeconds: 30
