apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: debug-disk
  labels:
    name: debug-disk
spec:
  selector:
    matchLabels:
      name: debug-disk
  template:
    metadata:
      labels:
        name: debug-disk
    spec:
      hostPID: true
      hostIPC: true
      tolerations:
      - key: node-role.kubernetes.io/master
        effect: NoSchedule
      containers:
      - name: debug
        image: jemartin1993/k8s-debug-pod:disk-0.0.1
        imagePullPolicy: Always
        command: ["/debug-disk"]
        resources:
          limits:
            memory: 200Mi
          requests:
            cpu: 100m
            memory: 200Mi
      terminationGracePeriodSeconds: 30
