apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: debug-disk
  labels:
    name: debug-disk
spec:
  selector:
    matchLabels:
      name: debug-disk
  template:
    metadata:
      labels:
        name: debug-disk
    spec:
      hostPID: true
      hostIPC: true
      tolerations:
      - key: node-role.kubernetes.io/master
        effect: NoSchedule
      containers:
      - name: debug
        image: adrianmo/k8s-debug-pod:0.6.3
        imagePullPolicy: Always
        command: ["/debug-disk"]
        env:
          - name: POD_SLEEP_SECS
            value: "30"
          - name: INSTRUMENTATION_KEY
            value: ""
          - name: NODE_NAME
            valueFrom:
              fieldRef:
                fieldPath: spec.nodeName
          - name: POD_NAME
            valueFrom:
              fieldRef:
                fieldPath: metadata.name
        resources:
          limits:
            memory: 200Mi
          requests:
            cpu: 100m
            memory: 200Mi
      terminationGracePeriodSeconds: 30
