# basic pod, runs for POD_SLEEP_SECS (defaut: 600) seconds then exits
apiVersion: v1
kind: Pod
metadata:
  name: basic-pod
spec:
  restartPolicy: Always
  containers:
    - name: sleeper
      image: busybox
      imagePullPolicy: Always
      command: [ "/bin/sh", "-c", "echo \"Sleeping for ${POD_SLEEP_SECS}...\" && date && sleep ${POD_SLEEP_SECS} && date && exit 0"]
      env:
        - name: POD_SLEEP_SECS
          value: "600"
